### ISSUE TITLE
Readme Schema file does not match schema.yaml

### ISSUE THREAD

**Issue by patrickml** [awslabs/open-data-registry#1051]
The schema defined here **https://github.com/awslabs/open-data-registry/blame/main/README.md#L19-L52**
Does not match the schema.yaml file laid out here https://github.com/awslabs/open-data-registry/blob/main/schema.yaml

**Comment by jflasher** [comment]
Hi @patrickml, thanks for reporting! Can you be more clear on what doesn't match? The latter is only used for schema validation so something we may not care to validate may be missing from that one, but in general, they should be pretty close or match.
