### ISSUE TITLE
Support retrieving partial data fragments

### ISSUE THREAD

**Issue by mmomtchev** [awslabs/open-data-registry#1079]
I am a regular user of NOAA's GFS datasets - I switched from NOAA's own distribution service to AWS since AWS tends to be much faster and more reliable. There is however once feature from NOAA's distribution service that I miss: making partial requests.

These files are absolutely huge and they usually have world-wide coverage with tons of parameters. Most users are interested only in one subregion and/or a handful of these parameters - I used to download only about 2% to 3% of the data.

I am one of authors and the current maintainer of GDAL for Node.js - the software that could serve these partial requests -  and I was wondering if it would be possible to host a web service that will serve partial requests for all geospatial datasets - including NOAA.

This would allow for huge bandwidth savings both for AWS and everyone who routinely downloads these datasets.

I will be willing to contribute the code should AWS accepts to host the service.

**Comment by zflamig** [comment]
Hi @mmomtchev 

S3 supports range gets so you can download a single variable at a time. See the example python function `download_variable` for this in [this notebook](https://github.com/awslabs/amazon-asdi/blob/main/examples/noaa-gfs-parquet/notebooks/GFS-Parquet-Athena.ipynb). 

Unfortunately there isn't a similarly easy way to do spatial subsetting. If you would like to discuss further please reach out to me via email at zlf @ amazon
