### ISSUE TITLE
Cannot access public dataset SPACENET

### ISSUE THREAD

**Issue by tayalkshitij** [awslabs/open-data-registry#110]
On `http://spacenet-dataset.s3.amazonaws.com/` , public s3 bucket is `arn:aws:s3:::spacenet-dataset.`
However when I try to access the bucket via https
`http://spacenet-dataset.s3.amazonaws.com/`, it is giving following error 
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>80AA03A4A2B74B07</RequestId>
<HostId>
vpeLzorRhAVQAc5WIy7aC9atGuyrgnBw+xdRR8GklvasUI4jgQ+Bd8Yl6Jo9QU5rQnbcMOkwxME=
</HostId>
</Error>
```

Is this dataset no longer public ?

**Comment by dlindenbaum** [comment]
Hello,

The dataset is public.  However it requires an aws account to access.

It can be accessed through the aws command line tool or through presigned links.

https://spacenetchallenge.github.io/ has instructions for ways to access the data sets 

Thank you,
Dave

**Comment by anujshah1003** [comment]
aws s3 ls s3://spacenet-dataset/SpaceNet_Roads_Competition/

I am getting below access denied message

An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied

**Comment by jflasher** [comment]
Hi @anujshah1003, that prefix does not exist so would be returning empty, however, it should not be throwing an error. Access to S3 requires permissions on both the bucket owner side (this is enabled) and the bucket accessor side. You own the permissions for the user you are using to access the bucket so it is likely that you need to enable the ability to read from S3 (in general or specifically for this bucket) via IAM in your account.
