### ISSUE TITLE
CCLE metatable

### ISSUE THREAD

**Issue by BastienNguyen** [awslabs/open-data-registry#1140]
Hello,
I know this bucket `s3://gdc-ccle-2-open/` is a mix of RNAseq/WES/WGS (https://registry.opendata.aws/ccle/) but I am struggling to find a metadata table specifying which .bam is what.
Could you please point me to the right place?

Thanks,

Bastien

**Comment by chueatwork** [comment]
Hi @BastienNguyen thanks for reaching out! I believe the indices for each experiment are unique to the Genomic Data Commons--as you want to use these data directly from S3, I suggest you email dcf-support@datacommons.io for assistance mapping metadata to experiment index. Let me know if you don't get a response!
