### ISSUE TITLE
resource out of date

### ISSUE THREAD

**Issue by blajoie** [awslabs/open-data-registry#1142]
Are there plans to sync the s3 data with the nih ftp?
ftp.ncbi.nlm.nih.gov/giab/ftp/release

e.g. FTP contains the NISTv4.2.1 benchmarking whereas this does not exist on s3.

**Comment by chueatwork** [comment]
Thanks @blajoie I will reach out to the data provider!

**Comment by chueatwork** [comment]
Thank you @chunlinxiao !
