### ISSUE TITLE
can you add my datasets to the repository?

### ISSUE THREAD

**Issue by FurkanGozukara** [awslabs/open-data-registry#1185]
here their links

https://github.com/FurkanGozukara/Record-Linkage

https://github.com/FurkanGozukara/Sentiment-Analysis

**Comment by jflasher** [comment]
Hi @FurkanGozukara, thanks for reaching out. This listing is a repository of publicly available datasets that are available for access from AWS resources. This data looks to be made available via GitHub, so it would not be a fit to list here. I am going to close this issue, but if I misunderstood anything, feel free to reopen, thanks!

**Comment by FurkanGozukara** [comment]
@jflasher how can I make it available from AWS resources? or maybe you can make it available?

**Comment by jflasher** [comment]
Hi @FurkanGozukara, we have no mechanism to make the data available for you. For this type of data, https://aws.amazon.com/s3/getting-started/ probably makes the most sense and there are instructions on getting started at that link. However, if you are happy with the data being on GitHub, you're probably fine to just leave it where it is.
