### ISSUE TITLE
the download url of Low Context Name Entity Recognition (NER) Datasets with Gazetteer is not available

### ISSUE THREAD

**Issue by diqiuzhuanzhuan** [awslabs/open-data-registry#1258]
When I tried to download the dataset according to readme, I found  that the downloaded file was a html file named after ”readme.html“
type the command as below:
 > aws s3 ls --no-sign-request s3://lowcontext-ner-gaz
it will say:
2021-04-29 00:22:58       2025 readme.html

only a readme.html

**Comment by jflasher** [comment]
@diqiuzhuanzhuan thanks again for reporting this and I am going to close this as the data is now back in place.
