### ISSUE TITLE
missing tiles for Copernicus DEM 30 meters

### ISSUE THREAD

**Issue by MarcYin** [awslabs/open-data-registry#1335]
The following tiles are missing from the [AWS Copernicus Digital Elevation Model](https://registry.opendata.aws/copernicus-dem/):

'N06_00_W163_00',
'N15_00_W079_00',
'N23_00_E037_00',
'N24_00_E036_00',
'S20_00_E164_00'

But they are available through the Copernicus FTP server.

Marc.

**Comment by jeffejefe** [comment]
Hi @MarcYin the data is maintained by Sinergise though it's possible @tomislijepcevic might have more information on that.

**Comment by tomislijepcevic** [comment]
These tiles were introduced in the latest 2021 Copernicus DEM release, while the data on AWS was from release 2019 when you checked it.

On Monday, we (Sinergise) upgraded the data to 2021 release, so these tiles are now available.

**Comment by jeffejefe** [comment]
@MarcYin see above comment. Thanks @tomislijepcevic for the quick response!
