### ISSUE TITLE
Access denied for NYC taxi dataset

### ISSUE THREAD

**Issue by scharlottej13** [awslabs/open-data-registry#1418]
Has access changed recently for the [NYC taxi and limo dataset](https://registry.opendata.aws/nyc-tlc-trip-records-pds/)? When I run `aws s3 ls --no-sign-request s3://nyc-tlc/` I'm getting an Access Denied error: `An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied`.

The bucket `nyc-tlc-trip-records-pds` works, but I think this is an older version since the files only go up to 2015.

@pschmied I noticed you recently edited the [yaml file](https://github.com/awslabs/open-data-registry/blob/8f0cb53876517fa3d5935946ac47d637e17bc3c2/datasets/nyc-tlc-trip-records-pds.yaml) for this dataset, any ideas?

Thanks in advance for the help!

**Comment by jflasher** [comment]
Hi @scharlottej13, thanks for reaching out! We noticed this as well and have reached out to the listed contact email of research@tlc.nyc.gov to work through this with them, but no response yet. I'd suggest reaching out to them as well, thanks!

**Comment by scharlottej13** [comment]
Will do, thanks @jflasher!

**Comment by rory-donaldson** [comment]
Hi all, is there any updates on this? I'm getting similar

**Comment by rory-donaldson** [comment]
Is this now the case for all open data registries that an AWS account is needed for access? 
I do have an account and can access when using credentials, but in this case I want to be able to stage data from public S3 bucket into Snowflake without going through the auth process, as it's for set up of an introductory teaching course.

**Comment by pschmied** [comment]
It varies by dataset, however any dataset that requires authentication to access will have an "account required" label on its landing page on the Registry of Open Data. 
<img width="1189" alt="account-required" src="https://github.com/awslabs/open-data-registry/assets/1065905/08e3b1ae-8906-4389-85cd-727242895afa">

**Comment by rory-donaldson** [comment]
Ok makes sense, thanks for this!

**Comment by kovi01** [comment]
@pschmied I am getting the Access denied error even after trying all the above steps.
Can you help me with this

**Comment by pschmied** [comment]
Hi @kovi01 , I think the issue is with the configuration of whatever S3 client you're using. I can confirm access is working as expected. Direct S3 access to the nyc-tlc S3 bucket requires a signed request. To sign a request, you'll need an AWS account. If, for example, you're using the AWS CLI, you'll need to make sure your AWS credentials are configured properly: https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html

Note that NYC TLC also maintains a website that links directly to the objects via CloudFront -> S3. You can find the CloudFront download links at the NYC TLC's documentation website linked from the Registry of Open Data, or directly here: https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page

**Comment by kovi01** [comment]
Hey @pschmied, Thanks for your response. I have tried to access it from my AWS account through the CLI after properly assigning the IAM roles and policies. Still the error is occuring. For your reference i put the screenshot of this.
<img width="485" alt="Capture" src="https://github.com/awslabs/open-data-registry/assets/56697341/7b6ee2ef-6a38-4619-9b3c-06d07b3c5da7">

**Comment by pschmied** [comment]
In your screenshot, you are including the `--no-sign-request` flag, which will prevent your AWS client from signing the request as required. If you drop that from your command invocation, you should be set.

Also, since you're using AWS CloudShell, you shouldn't need to worry about manually setting your Access Key or Secret Access Key, and the AWS CLI should pick up your credentials from the CloudShell environment.

**Comment by kovi01** [comment]
Well! Its working now with CLI. However my concern is in my code its not accessing.
<img width="604" alt="Capture" src="https://github.com/awslabs/open-data-registry/assets/56697341/e728a68c-8bc3-4474-a7c9-36de081499f7">
It would be great if you could help me with this.

**Comment by DushaevSirojiddin** [comment]
<img width="762" alt="image" src="https://github.com/awslabs/open-data-registry/assets/96657951/4cde95e4-3c1f-4948-892c-ca35fee2a438">

I am getting this error, I gave all s3 permissions to the user, even with the root user I am getting this error

<img width="665" alt="image" src="https://github.com/awslabs/open-data-registry/assets/96657951/09fbd188-352d-4a57-9d8c-33651a919396">

**Comment by DushaevSirojiddin** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/userguide/troubleshoot-403-errors.html#troubleshoot-403-tips?icmpid=docs_amazons3_console

<img width="1512" alt="image" src="https://github.com/awslabs/open-data-registry/assets/96657951/5e00e787-886e-425e-b472-7baea1337f02">

**Comment by pschmied** [comment]
Thank you, @DushaevSirojiddin — this appears to be a different issue, and looks like a change with the data provider. I'll reach out to them to see if they have changed something.

**Comment by lykmapipo** [comment]
> Thank you, @DushaevSirojiddin — this appears to be a different issue, and looks like a change with the data provider. I'll reach out to them to see if they have changed something.

Thank you, @pschmied --- Any updates from the data provider?

**Comment by djpirra** [comment]
Any updates on this topic? Was trying to access using a policy and an access key and it does not work :(

**Comment by MaxPowerWasTaken** [comment]
I am also getting `An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied` when running `aws s3 ls s3://nyc-tlc` (i.e. without the `--no-sign-request` option. I am getting the same error both from the (properly configured/authenticated) aws cli on my local machine, and on aws cloud shell in us-east-1 (where the nyc-tlc bucket is as well).

**Comment by vsoldera** [comment]
This is not working.

**Comment by jovezhong** [comment]
I am about to do some perf test for large ETL pipeline and the NYC taxi data looks meaningful. I can download those large parquet files (such as fhvhv_tripdata_2025-01.parquet is 466MB) but the S3 bucket cannot be listed. I am about to download those files via wget and put in my own s3 bucket for testing. Just change the year/month in such wget
`wget https://d37ci6vzurychx.cloudfront.net/trip-data/fhvhv_tripdata_2025-01.parquet`

**Comment by jovezhong** [comment]
Here is the script https://github.com/jovezhong/large_etl/blob/main/cmd.sh About 30GB parquet files. Good enough for my test. You can setup own bucket and modify the script in whatever way. The script is mostly written by AI (vibe coding?), I just fixed 10% of them.

**Comment by jamessewell** [comment]
This doesn't work for me:

```
[nix-shell:/]$ aws configure list 
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                <not set>             None    None
access_key     ****************5TO6 shared-credentials-file    
secret_key     ****************ItAf shared-credentials-file    
    region                us-east-1      config-file    ~/.aws/config

[nix-shell:/]$ aws s3 ls s3://nyc-tlc/

An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
```

I can use my account to do things like describe ec2 servers, so the auth is working properly.

**Comment by jovezhong** [comment]
Hi @jamessewell , it's confirmed the bucket nyc-tlc is no longer publicly available. You can download those parquet files by yourself, you can check my comments and sample code above.
