### ISSUE TITLE
arn:aws:s3:::ooni-data-eu-fra

### ISSUE THREAD

**Issue by kjmoutlook** [awslabs/open-data-registry#1464]
https://github.com/awslabs/open-data-registry/blob/3684c95dc037f6df6eccb7319b3228f7ed613abe/datasets/ooni.yaml

aws s3 ls --no-sign-request s3://ooni-data/

arn:aws:s3:::ooni-data

aws s3 ls --no-sign-request s3://ooni-data-eu-fra/

arn:aws:s3:::ooni-data-eu-fra

**Comment by kjmoutlook** [comment]
245753810638
KingOfTheArmy

**Comment by jflasher** [comment]
Closing as spam, please reopen if otherwise.
