### ISSUE TITLE
Typo in Description for some NOAA yaml

### ISSUE THREAD

**Issue by ewb4** [awslabs/open-data-registry#1473]
Likely typo in protocol in url listed in the description in the following .yaml files:

- noaa-cdr-atmospheric.yaml
- noaa-cdr-fundamental.yaml
- noaa-cdr-oceanic.yaml
- noaa-cdr-terrestrial.yaml

**Comment by cstner** [comment]
Fix submitted today for all 4 yamls - thanks for your feedback!
