### ISSUE TITLE
the usaspending snapshot has been removed

### ISSUE THREAD

**Issue by RZachLamberty** [awslabs/open-data-registry#158]
I might be mistaken, but based on [this comment](https://usaspending-help.zendesk.com/hc/en-us/community/posts/360010347313/comments/360001394614) and the fact that [the download instructions](https://files.usaspending.gov/database_download/) on the usaspending site have changed, it seems that the snapshot is no longer available.

given that, it would be nice if the documentation here reflected that.

**Comment by jedsundwall** [comment]
Thanks for the heads up. We’ll remove the listing for USASpending.gov from the registry until they make the new S3-based version available.

**Comment by jedsundwall** [comment]
Removed with PR https://github.com/awslabs/open-data-registry/pull/159.
