### ISSUE TITLE
GOES16 legacy temperature profile data problems

### ISSUE THREAD

**Issue by stiposentic** [awslabs/open-data-registry#1607]
GOES16 legacy temperature profiles have weird offsets when I load the netcdf file in many programs (I am up to date with netcdf4 libraries). For example, in the attached file I show a profile of the temperature at point nx=500, ny=500 of the file listed in the title of the figure. Offset occurs from points 1 to 37, and 86 to 97. Is this issue known for these ABI products? The figure shows a profile from aws depository s3://noaa-goes16/ABI-L2-LVTPF/2020/255/00/OR_ABI-L2-LVTPF-M6_G16_s20202550000196_e20202550009504_c20202550011454.nc
One possible problem I see is that the valid range for the LVM variable is "LVM:valid_range = 0s, -6s ;" I have never seen this before. Any suggestions?
![188037659-7cada56a-459f-4e39-b207-24825dbc1ba8](https://user-images.githubusercontent.com/20520726/196465406-058b32b4-06ee-4e02-b035-5e2a4827f4a9.png)

**Comment by jflasher** [comment]
Hi @stiposentic, thanks for raising this question. We are trying to get folks to move over to re:Post for asking these questions, would you be able to ask this at https://repost.aws/tags/TApd0Wl5P8S9O6riTWmh-cGw/aws-open-data and tag it with "Open Data?" Ultimately, this is a question for NOAA and we will make them aware of the presence of the question, thanks!
