### ISSUE TITLE
Missing NOAA GHCN daily data for 2023

### ISSUE THREAD

**Issue by vilen** [awslabs/open-data-registry#1711]
Hi,

it seems that nooa-ghcn-pds [bucket](https://noaa-ghcn-pds.s3.amazonaws.com/index.html#csv.gz/by_year/) is missing aggregated data for 2023 in the `by_year/` folder. Any ideas when it might become available?

Thank you!

**Comment by badjouras** [comment]
Tagging @Patrick-Keown , as he seems to be a point of contact from NOAA.

**Comment by vilen** [comment]
Now the bucket has 2023 data. Thank you!
