### ISSUE TITLE
Raster data class categories information

### ISSUE THREAD

**Issue by dmatekenya** [awslabs/open-data-registry#1856]
This is the ARN for the dataset: arn:aws:s3:::io-10m-annual-lulc with the following [URL](https://registry.opendata.aws/io-lulc/)

I'm attempting to use the dataset for the first time but I can't seem to find the conversion between the numeric (integer) pixel values and their corresponding class names. I know the rasters have 9 classes: Built, Crops, Trees, Water, Rangeland, Flooded Vegetation, Snow/Ice, Bare Ground, and Clouds. So, all I need is that dictionary which says {0: Built, 1: Crops.....}. Also, the list mentioned on the dataset abstract (Built, Crops, Trees, Water, Rangeland, Flooded Vegetation, Snow/Ice, Bare Ground, and Clouds) has 10 classed, not 9. I have visited the documentation site but it doesn't seem to have this information or I'm somehow missing it.

Any help will be appreciated. 

Thanks,
Dunstan

**Comment by jeffejefe** [comment]
Hi @dmatekenya I believe this is what you might be looking for: https://docs.impactobservatory.com/io-lulc-maps/io-lulc-maps.html. It shows the 9 category LULC definition with the integer class associated noting that values 3 and 6 aren't used. Also no data has an integer class but isn't a LULC category. You can also see the class definitions here: https://www.arcgis.com/home/item.html?id=30c4287128cc446b888ca020240c456b

**Comment by jeffejefe** [comment]
Hi @dmatekenya I am closing this issue for now but feel free to open it up as needed.
