### ISSUE TITLE
Error when trying to read smithsonian-open-access bucket

### ISSUE THREAD

**Issue by villanueval** [awslabs/open-data-registry#1913]
When trying to do `ls` on the smithsonian-open-access bucket I'm getting an error. I tried on my machine and the AWS console cloudshell:

```bash
$ aws s3 ls --no-sign-request s3://smithsonian-open-access/

An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
```

The command is the one that appears in the page https://aws.amazon.com/marketplace/pp/prodview-hrapqhkdh2w4s

Maybe a misconfigured bucket?

**Comment by cstner** [comment]
Hi Luis, Can you check the Permissions tab, and make sure that Block public Access is turned off. Also compare the bucket policy to the CloudFormation template in the Onboarding Handbook: https://assets.opendata.aws/aws-onboarding-handbook-for-data-providers-en-US.pdf

**Comment by villanueval** [comment]
Thanks, I was able to find the right contact and they fixed the permissions. Closing the issue since it is available again.
