### ISSUE TITLE
Open Data Sponsorship Program, Argo marine dataset

### ISSUE THREAD

**Issue by tcarval** [awslabs/open-data-registry#1964]
@cstner 
Hello Chris, here is the YAML description of Argo GDAC marine floats data and its associated logo.
If correct, can you register it on AWS Open Data directory ?
Thank you for your help.

- [argo-gdac-marinedata.zip](https://github.com/awslabs/open-data-registry/files/12313242/argo-gdac-marinedata.zip)
- The Argo program logo
![Argo_logo_tallspacer](https://github.com/awslabs/open-data-registry/assets/19821468/abe3182d-f900-4682-bc79-4b15052b38c1)

**Comment by cstner** [comment]
hi there - can you post the yaml as a file not part of a zip?   And I have copied down the logo so you can remove it from here.

**Comment by tcarval** [comment]
Hello Chris, I watched the video and created this pull request https://github.com/awslabs/open-data-registry/pull/1969

**Comment by tcarval** [comment]
Thank you Chris for your support on Argo dataset registration on ASDI 🙂
