### ISSUE TITLE
Two Sentinel-2 Documentation Links

### ISSUE THREAD

**Issue by jedsundwall** [awslabs/open-data-registry#201]
There are two links to documentation on the Sentinel-2 dataset, and if you click on it, it will attempt to open this URL:

`https://roda.sentinel-hub.com/sentinel-s2-l1c/readme.html,https://roda.sentinel-hub.com/sentinel-s2-l2a/readme.html`

Obviously, this doesn't resolve. How do we accommodate multiple links to documentation? Could we allow links or Markdown in the Documentation field?

**Comment by jflasher** [comment]
We currently only allowed links. Since they'll work nicely if we switch to markdown, I don't see any reason not to go that route. Updating the browser to support, also updating the schema and the sentinel-2.yaml to take advantage of that.
