### ISSUE TITLE
Add Landsat 5 and 7 datasets

### ISSUE THREAD

**Issue by adamjstewart** [awslabs/open-data-registry#222]
Has anyone looked into adding Landsat 5 and 7 to AWS?

Landsat provides the longest running continuous earth observation system in history. Although Landat 8 is great, it only provides data from 2013 and on. Most studies involving long term trends like climate change require decades of satellite imagery.

What would be involved in getting Landsat 5 and 7 on AWS and who would I talk to?

**Comment by jflasher** [comment]
Hi @adamjstewart, totally agree with you on the value of older Landsat data. USGS has publicly stated that they are looking at providing their data in multiple ways, including on AWS. I think the best way to help this effort at the moment would be to reach out to them via their [Contact page](https://answers.usgs.gov/) and let them know where and how you would like to see the data be made available. Hope that helps!

**Comment by adamjstewart** [comment]
I contacted USGS EROS and this was their official response:

> Landsat ETM and TM are not currently available on AWS. However, there is a product working on doing so. Rough estimate for completion is about 1 to 1.5 years.

Since this is already a work in progress and far off, I'll close this issue.

**Comment by jflasher** [comment]
Thanks @adamjstewart!
