### ISSUE TITLE
have a list of catalog ids for Digital Globe Open Data

### ISSUE THREAD

**Issue by d3netxer** [awslabs/open-data-registry#283]
hi, is there a way to get a list of catalog IDs for the imagery released for a Digital Globe Open Data event? (Cyclone Idai)

There are over 100 imagery strips listed for this event on https://www.digitalglobe.com/ecosystem/open-data/cyclone_idai and I would like to save some time by not parsing them.

getting some basic metadata with the ids as well would be a plus (date, sensor, cloud cover, etc), but I think catalog IDs are a good start.

Actually, it would be a plus plus if we could get the imagery extents as well (geojson or shapefile).

**Comment by jflasher** [comment]
Hi @d3netxer, thanks for the question. I think this aligns well with work that groups have been doing around https://github.com/radiantearth/stac-spec, but this is really a question for DigitalGlobe as they're the owners of this data. I've made them aware of this issue. I'm going to close this for now as there is no action we can take on it, but feel free to re-open if you have other questions.
