### ISSUE TITLE
IRS 990 contact link throwing 404

### ISSUE THREAD

**Issue by chadokruse** [awslabs/open-data-registry#288]
@jedsundwall Was trying to find contact info for the IRS folks to alert them of an error in their indexes and noticed the existing link at [the registry site](https://registry.opendata.aws/irs990/) is throwing a 404. 

The best link I could find was [this one](https://www.irs.gov/e-file-providers/e-file-for-charities-and-non-profits)?

In case the fine folks at the IRS read this, the 2018 indexes are currently out of sync (e.g. the 2018 CSV index shows 457,509 records while the 2018 JSON index shows just 432,801).

**Comment by jedsundwall** [comment]
Thank you for this! I’ll notify the IRS about this.
