### ISSUE TITLE
NPPES Dataset hosting

### ISSUE THREAD

**Issue by napalm684** [awslabs/open-data-registry#305]
I would like to suggest adding the NPPES NPI registry.  It is a national registry for prescribers publicly available and incredibly useful/critical to healthcare/medical organizations.

https://npiregistry.cms.hhs.gov/

**Comment by jflasher** [comment]
Hi @napalm684, thanks for making the suggestion! This registry is for datasets that are made available through native AWS interfaces (like S3 or CloudFront). If that's the case here, then we can look at getting it added. Or if you are recommending that the data be made available on S3, you should check out https://aws.amazon.com/opendata/public-datasets/. We are always looking to work with providers to make more data available in cloud-optimized formats on AWS.
