### ISSUE TITLE
License / citation for GIAB is private

### ISSUE THREAD

**Issue by illusional** [awslabs/open-data-registry#323]
I'm unable to access the license / citation information in the GIAB registry, per the [AWS giab registry](https://registry.opendata.aws/giab/):

> There are no restrictions on the use of this data. More information on citation is available [here](https://sites.stanford.edu/abms/content/giab-reference-materials-and-data).

The here is https://sites.stanford.edu/abms/content/giab-reference-materials-and-data which is blocked by a sign in page. I know it was a while ago @jflasher, but do you have any information about this?

**Comment by zflamig** [comment]
Check the official GIAB page for more info: https://www.nist.gov/programs-projects/genome-bottle or reach out to them if you have more questions about the license/citation. 

We will fix the link asap too.

**Comment by zflamig** [comment]
Link updated in #324, closing this as resolved.
