### ISSUE TITLE
Incorrect AWS region for GIAB dataset?

### ISSUE THREAD

**Issue by jzook** [awslabs/open-data-registry#336]
At  https://registry.opendata.aws/giab/ 
and in the giab.yaml file at
https://github.com/awslabs/open-data-registry/tree/master/datasets  
the AWS region for bucket=giab is listed as us-east-1.

However, when I try to access the bucket via the AWS Java API or at
https://giab.s3.us-east-1.amazonaws.com/
AWS returns "The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2' " (or similar from the URL).

If I try https://giab.s3.us-west-2.amazonaws.com/
it succeeds.

Can you please investigate and perhaps change the yaml file so the region is listed as us-west-2?

Thank you!

**Comment by zflamig** [comment]
Thanks for the report! Fixed in #337
