### ISSUE TITLE
Possible to add CORS to Genome-in-a-Bottle dataset?

### ISSUE THREAD

**Issue by cmdcolin** [awslabs/open-data-registry#344]
Hi there,
I was wondering if it would be possible to add CORS settings to the genome-in-a-bottle dataset

https://github.com/genome-in-a-bottle/giab_latest_release/issues/10#issuecomment-530191566

It is very helpful to test our demo datasets like GIAB, but it requires CORS

I think something like this would be ideal, I had talked previously with an AWS admin when settings like this were added to the 1000genomes s3 bucket

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedHeader>Range</AllowedHeader>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <ExposeHeader>Accept-Ranges</ExposeHeader>
        <ExposeHeader>Content-Range</ExposeHeader>
        <ExposeHeader>Content-Encoding</ExposeHeader>
        <ExposeHeader>Content-Length</ExposeHeader>
        <AllowedHeader>Authorization</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
```

**Comment by chueatwork** [comment]
Hi cmcolin, CORS has been enabled for the GIAB bucket, apologies for the long delay in response. Please feel free to contact with any additional questions.

**Comment by cmdcolin** [comment]
Awesome thanks. I was trying a little test but unsure if I am using it right

I tried

https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=http%3A%2F%2Fgiab.s3.amazonaws.com%2Fdata%2FAshkenazimTrio%2FHG003_NA24149_father%2FNIST_Stanford_Illumina_6kb_matepair%2Fbams%2FHG003.mate_pair.bam.bai&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote

This does not give a successful request. Is there a different URL format I should request from?
