### ISSUE TITLE
Can't download SpaceNet Buildings Dataset v1

### ISSUE THREAD

**Issue by bessszilard** [awslabs/open-data-registry#456]
I am trying to download [SpaceNet Buildings Dataset v1](https://spacenetchallenge.github.io/datasets/spacenetBuildings-V1summary.html) 

I ran the suggested command in a Sagemaker notebook, and I got this error.

Command:
```bash
$ aws s3 cp s3://spacenet-dataset/SpaceNet_Roads_Competition/AOI_2_Vegas_Roads_Train.tar.gz 
```

Error:
`
fatal error: An error occurred (404) when calling the HeadObject operation: Key "SpaceNet_Roads_Competition/AOI_2_Vegas_Roads_Train.tar.gz" does not exist
`
 
I tried this with Paris data as well, and I got the same error. I found this [repo](https://github.com/SpaceNetChallenge/utilities/issues), but it has achieved by the owner, so I put there any issue.

How can I download this dataset properly?

**Comment by pschmied** [comment]
Hello,

It looks like you are viewing an outdated version of the documentation. The Registry of Open Data currently lists [https://spacenet.ai/](https://spacenet.ai/) as the source for documentation.

If you have any further questions about this dataset or the documentation, please feel free to contact SpaceNet directly, as they manage this dataset.

Best,
Peter

**Comment by Fatemeh90** [comment]
Please, if this dataset is publicly available for free, kindly provide a direct download link, as I was also unable to download it from the Amazon website.  
Thank you.
Best
