### ISSUE TITLE
Update http://990.charitynavigator.org?

### ISSUE THREAD

**Issue by jedsundwall** [awslabs/open-data-registry#50]
@borenstein - I'm looking at [the entry for the 990 data](https://github.com/awslabs/open-data-registry/blob/master/datasets/irs990.yaml) and it seems that http://990.charitynavigator.org may be stale at this point. Should we replace that with a pointer to https://github.com/CharityNavigator/990_long?

If you think so, please feel free to create a pull request or let me know if you'd like me to.

**Comment by borenstein** [comment]
@jedsundwall good idea. Pull request created.

--
David Bruce Borenstein, PhD
781.710.2789 (m)
https://www.linkedin.com/in/davidborenstein

**Comment by jedsundwall** [comment]
Thanks! Just accepted https://github.com/awslabs/open-data-registry/pull/51.
