### ISSUE TITLE
noaa-ghe data timeliness

### ISSUE THREAD

**Issue by vcabbage** [awslabs/open-data-registry#525]
We've observed that currently the latest GHE data available in S3 is s3://noaa-ghe-pds/rain_rate/2020/04/20/NPR.GEO.GHE.v1.S202004201230.nc.gz. NOAA currently has https://satepsanone.nesdis.noaa.gov/pub/HydroEst/GHE/NPR.GEO.GHE.v1.S202004201430.nc.gz available.

Is there perhaps an issue with the ingestion to S3?

Thank you.

**Comment by zflamig** [comment]
The data provider has informed us this is due to maintenance work. Check out the bulletin at https://www.ospo.noaa.gov/data/messages/2020/MSG111122402.html

**Comment by vcabbage** [comment]
Thank you! That information is very much appreciated. Do you want to close this ticket now or wait until data is coming in again? Either is fine by me.

**Comment by zflamig** [comment]
Lets go ahead and close this. I've got a question on the impact of this to what you are doing though if you want to shoot me an email zlf@amazon.com
