### ISSUE TITLE
CSV data is missing from dataforgood-fb-data bucket

### ISSUE THREAD

**Issue by luciferlu** [awslabs/open-data-registry#545]
The csv prefix is missing from bucket dataforgood-fb-data. I cannot load partition from Athena.
I created the table by using:
```
CREATE EXTERNAL TABLE IF NOT EXISTS default.hrsl (
  `latitude` double,
  `longitude` double,
  `population` double 
) PARTITIONED BY (
  month string,
  country string,
  type string 
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
  'serialization.format' = '\t',
  'field.delim' = '\t'
) LOCATION 's3://dataforgood-fb-data/csv/'
TBLPROPERTIES ('has_encrypted_data'='false', 'skip.header.line.count'='1');
```

Then load partitions by using:
`MSCK REPAIR TABLE hrsl;`

But I got this error message: 
`Tables missing on filesystem:	hrsl`

**Comment by pschmied** [comment]
Thank you for reporting. The data provider was notified and has fixed the issue.

**Comment by luciferlu** [comment]
Thanks for helping, the data files has been updated on the bucket, but looks like all "latitude", "longitude" and "population" columns are all empty.

**Comment by pschmied** [comment]
Hello, I just attempted to reproduce, and it appears that the restored files are now in comma delimited format rather than tab delimited format. I will let the data provider know. They may choose to address by updating the documentation or changing back to a tab delimited format.

In the meantime, you should be able to query the CSV format data by recreating your Athena table:

```
CREATE EXTERNAL TABLE IF NOT EXISTS default.hrsl (
  `latitude` float,
  `longitude` float,
  `population` float 
) PARTITIONED BY (
  month string,
  country string,
  type string 
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
  'serialization.format' = ',',
  'field.delim' = ','
) LOCATION 's3://dataforgood-fb-data/csv/'
TBLPROPERTIES ('has_encrypted_data'='false');
```

Of course if the data provider elects to revert the files to a tab-delimited format, you would need to recreate the table once again.

**Comment by luciferlu** [comment]
> Hello, I just attempted to reproduce, and it appears that the restored files are now in comma delimited format rather than tab delimited format. I will let the data provider know. They may choose to address by updating the documentation or changing back to a tab delimited format.
> 
> In the meantime, you should be able to query the CSV format data by recreating your Athena table:
> 
> ```
> CREATE EXTERNAL TABLE IF NOT EXISTS default.hrsl (
>   `latitude` float,
>   `longitude` float,
>   `population` float 
> ) PARTITIONED BY (
>   month string,
>   country string,
>   type string 
> )
> ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
> WITH SERDEPROPERTIES (
>   'serialization.format' = ',',
>   'field.delim' = ','
> ) LOCATION 's3://dataforgood-fb-data/csv/'
> TBLPROPERTIES ('has_encrypted_data'='false');
> ```
> 
> Of course if the data provider elects to revert the files to a tab-delimited format, you would need to recreate the table once again.

You are right. Thanks for helping.
