### ISSUE TITLE
Glue Crawler

### ISSUE THREAD

**Issue by coingraham** [awslabs/open-data-registry#55]
Attempting to crawl this location with Glue pointed at the ARN produces an Access Denied issue.  What's the correct way to configure this?

I tried giving Glue more permissions (all the way to Admin) to no avail.

**Comment by jflasher** [comment]
Hi @coingraham, which specific dataset are you looking to crawl?

**Comment by coingraham** [comment]
My bad.  I was testing with the Coin Metrics data here "arn:aws:s3:::dataworld-odaws-us-east-1/datasets/scuttlemonkey/coin-metrics/"

**Comment by jflasher** [comment]
@coingraham looks like the underlying object that is trying to be accessed at the key is not publicly readable. I'll mention this to data.world who manages this dataset.

**Comment by sya** [comment]
Hi @coingraham. Sorry for the trouble. They should be accessible now.

**Comment by coingraham** [comment]
Confirmed working.  Thanks everyone.

**Comment by jflasher** [comment]
Thanks @sya!
