### ISSUE TITLE
Feature Request: add link to AWS S3 Explorer for each dataset

### ISSUE THREAD

**Issue by raybellwaves** [awslabs/open-data-registry#659]
Each dataset lists where the data resides e.g. taking NOAA GOES https://registry.opendata.aws/noaa-goes/

It's lists the location of the data e.g. 'noaa-goes16'.

It would be great if that link is hyper-linked to the AWS S3 Explorer so you can easily see what the files look like e.g. hyperlink to https://noaa-goes16.s3.amazonaws.com/index.html

<img width="1186" alt="Screen Shot 2020-09-04 at 6 13 14 PM" src="https://user-images.githubusercontent.com/17162724/92288325-9945ef80-eeda-11ea-95f8-3c6c29cd484e.png">

**Comment by raybellwaves** [comment]
Probably need to update the template as well to specify the requirement for the hyperlink for new datasets.

**Comment by jflasher** [comment]
:wave: @raybellwaves, thanks for the comment! We're with you on the idea of making it easier to point out ways for people to interact with the data. We have an open issue at https://github.com/awslabs/open-data-registry-browser/issues/131 to capture this. I am going to close this as our implementation would likely be a bit different, but same goal! Thanks again for taking the time to raise the issue.
