### ISSUE TITLE
Speedtest by Ookla Global Fixed and Mobile Network Performance Maps

### ISSUE THREAD

**Issue by dled** [awslabs/open-data-registry#695]
### Speedtest by Ookla Global Fixed and Mobile Network Performance Map Tiles

Request to add the following entries and additional tags related to the Speedtest Global Performance Maps dataset.

**Dataset entry**

`speedtest-global-performance.yaml`

**Add tags**

broadband, global, telecommunications, tiles

**Comment by pschmied** [comment]
Closing as previously merged.
