### ISSUE TITLE
"Swiss Public Transport Stops" access denied with aws cli against s3?

### ISSUE THREAD

**Issue by tooptoop4** [awslabs/open-data-registry#774]
https://registry.opendata.aws/schweizer-haltestellen-oev/

 aws s3 ls s3://data.geo.admin.ch/ch.bav.haltestellen-oev/ --no-sign-request

An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

**Comment by jflasher** [comment]
Thanks for reporting. If you're looking to access the data, you can do so using

`aws s3 cp s3://data.geo.admin.ch/ch.bav.haltestellen-oev/data.zip .`

I am going to close this as the UI part of this bug should be handled in `open-data-registry-browser`, opened https://github.com/awslabs/open-data-registry-browser/issues/163.
