### ISSUE TITLE
How to set "AWS_NO_SIGN_REQUEST=YES"?

### ISSUE THREAD

**Issue by JenniferYingyiWu2020** [awslabs/open-data-registry#794]
Hi,
    I encountered below errors when fetching data for one of: GDALRasterSource(s3://s22s-test-geotiffs/luray_snp/SCL.tif), GDALRasterSource(s3://s22s-test-geotiffs/luray_snp/B01.tif), GDALRasterSource(s3://s22s-test-geotiffs/luray_snp/B02.tif), GDALRasterSource(s3://s22s-test-geotiffs/luray_snp/B03.tif), GDALRasterSource(s3://s22s-test-geotiffs/luray_snp/B04.tif), GDALRasterSource(s3://s22s-test-geotiffs/luray_snp/B05.tif), GDALRasterSource(s3://s22s-test-geotiffs/luray_snp/B06.tif), GDALRasterSource(s3://s22s-test-geotiffs/luray_snp/B07.tif), GDALRasterSource(s3://s22s-test-geotiffs/luray_snp/B08.tif), GDALRasterSource(s3://s22s-test-geotiffs/luray_snp/B09.tif), GDALRasterSource(s3://s22s-test-geotiffs/luray_snp/B11.tif), GDALRasterSource(s3://s22s-test-geotiffs/luray_snp/B12.tif):
"
FAILURE(3) CPLE_AWSInvalidCredentials(15) "AWSInvalidCredentials." AWS_SECRET_ACCESS_KEY and AWS_NO_SIGN_REQUEST configuration options not defined, and /root/.aws/credentials not filled

py4j.protocol.Py4JJavaError: An error occurred while calling o142.collectToPython.
"
    After my searching on the Internet, I run the command to confirm whether the issue related about "AWS account".
![3](https://user-images.githubusercontent.com/72843232/104142000-72ea1080-53f4-11eb-97af-cc0cb5328028.png)
    Some programmers suggest to "try setting AWS_NO_SIGN_REQUEST=YES", but I am so confused how to set "AWS_NO_SIGN_REQUEST=YES". So, could you pls give me some suggestions? Thanks!

**Comment by jflasher** [comment]
Hi @JenniferYingyiWu2020 Unfortunately, this is more of a tooling question than an AWS question, but I will try to help as much as I can. First, you need to make sure that whatever account you are using has permissions to access the s3://s22s-test-geotiffs bucket. In cases where the bucket is publicly available (e.g., s3://landsat-pds) you can access the bucket anonymously. You can test this with

```aws s3 ls s3://landsat-pds --no-sign-request```

If the bucket is not publicly available or has the Requester Pays option turned on, you will need to authenticate in some way to access the data. You will not be able to use --no-sign-request (either via command line or via setting AWS_NO_SIGN_REQUEST option). It is free to create an AWS account to get the credentials you need, but note that there may be data request/egress charges depending on what bucket you are trying to access.

So the first question would be, what is the s3://s22s-test-geotiffs bucket, who owns it and is it publicly available? Note, I tried to access this bucket and was unable, so it likely is not publicly available which means you can not access it anonymously and can not use --no-sign-request.

Hope that helps!
