### ISSUE TITLE
To download 5% of cse-cic-ids2018 dataset

### ISSUE THREAD

**Issue by aktaseren** [awslabs/open-data-registry#799]
How can I download only 5% of cse-cic-ids2018 dataset since the storage in my local mac machine is not available to download all this 220 GiB dataset?

**Comment by jflasher** [comment]
Hi @aktaseren, you can see all the contents by using the CLI or and SDK like below

```aws s3 ls s3://cse-cic-ids2018/ --no-sign-request --recursive```

You can download individual files that may be of interest and fit within your space limitations. You can also use something like https://aws.amazon.com/ec2/ to spin up a machine with the necessary space and work with the data at scale.

Hope that helps and I am going to close this, but feel free to let us know if you have any other questions.
