### ISSUE TITLE
Please help with noaa-ncn.yaml not showing Explorer link 

### ISSUE THREAD

**Issue by irasellars** [awslabs/open-data-registry#826]
Dear @zflamig,
Could you please help us? 
I do not know the reason why the Explorer link (under Resources on AWS section on the right) is empty. The noaa-ncn.yaml has this information:

Resources:
  - Description: "[NCN Data and Products](https://geodesy.noaa.gov/CORS/data.shtml)"
    ARN: arn:aws:s3:::noaa-cors-pds
    Region: us-east-1
    Type: S3 Bucket
    Explore: "[Browse NOAA-NCN Bucket](https://noaa-cors-pds.s3.amazonaws.com/index.html)"

Thank you very much for your time and help.
Sincerely,
Ira.Sellars

**Comment by zflamig** [comment]
Fixed in #827

**Comment by irasellars** [comment]
Dear Zac,
Thank you very much for your help. I obviously didn't read the instruction about metadata requirements :)
Thank you once again.
