### ISSUE TITLE
AWS IoT endpoint?

### ISSUE THREAD

**Issue by TheSkorm** [awslabs/open-data-registry#846]
Sondehub provides users with a AWS IoT MQTT websocket stream to make use realtime streaming data.

We provide this via a presigned URL (from api gateway / lambda) : https://github.com/projecthorus/sondehub-infra/wiki/API-(Beta)#-get--sondeswebsocket and also via our python SDK.

Would having this as a resource be useful for this project? I'm not exactly sure how it would be expressed in the schema.

**Comment by zflamig** [comment]
There is an option for "cloudfront distribution" which would be a pretty close match for this. You can provide the URL to get the presigned url there and an explanation for what it is. An example of this is at https://github.com/awslabs/open-data-registry/blob/main/datasets/digital-globe-open-data.yaml
