### ISSUE TITLE
VRT file in 's3://dataforgood-fb-data/cog/hrsl_population/' has wrong filenames

### ISSUE THREAD

**Issue by sid-ks** [awslabs/open-data-registry#854]
Hi guys,

Thanks for all your efforts in maintaining the Open-Data-Registry.

While accessing the 'cog_global_population_2019-07-01.vrt' file inside folder 's3://dataforgood-fb-data/cog/hrsl_population/' via Rasterio.open() and checking a few sites across the globe, I got the below error -

```
Read or write failed. '/vsis3/dataforgood-fb-data/cog/hrsl_population/population_global_lat_50_lon_-10_2019-07-01.tif' does not exist in the file system, and is not recognized as a supported dataset name.
```

I went to 'aws cli' and did a 'grep', and found that all COG filenames start with "cog_population_global", whereas in the error it says "population_global".

I then downloaded the above VRT and found that almost **half** of the filenames are wrong, and are missing the "cog_" part of their names.

One example below -

```
<ComplexSource>
      <SourceFilename relativeToVRT="1">population_global_lat_70_lon_-150_2019-07-01.tif</SourceFilename>
      <SourceBand>1</SourceBand>
      <SourceProperties RasterXSize="20608" RasterYSize="1024" DataType="Float64" BlockXSize="256" BlockYSize="256" />
      <SrcRect xOff="0" yOff="0" xSize="20608" ySize="1024" />
      <DstRect xOff="108849" yOff="3762" xSize="20608" ySize="1024" />
      <NODATA>nan</NODATA>
    </ComplexSource>
```

Hope you guys notice this issue and fix it?

Thanks again for your efforts! :)

**Comment by jflasher** [comment]
Thanks for comment @sid-ks! I'm adding @migurski here who helped make this data available.

**Comment by migurski** [comment]
Thanks @jflasher and @sid-ks! Andi & team are looking at this.

**Comment by andi-g** [comment]
Thanks a lot for the feedback, @sid-ks! We're working on replacing the old COGs. The ones currently up on AWS were from a test-upload of an older version of HRSL. Apologies for the confusion. We're hoping to have the next version up within the next couple of weeks. In the meantime, the files on the Humanitarian Data Exchange are up to date (https://data.humdata.org/organization/facebook?sort=metadata_modified%20desc). We're changing our publishing workflow to a single stream: from us to AWS, and from there to HDX, but that process hasn't been completed yet.

**Comment by sid-ks** [comment]
Hey guys! Any update on this? Thank you!

**Comment by andi-g** [comment]
This folder is deprecated: s3://dataforgood-fb-data/cog
This is the new folder: s3://dataforgood-fb-data/hrsl-cogs/

See https://registry.opendata.aws/dataforgood-fb-hrsl/
